//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetail
    {
        public int ID { get; set; }
        public string stuID { get; set; }
        public Nullable<int> TeaID { get; set; }
        public Nullable<System.DateTime> fillTime { get; set; }
        public string isCough { get; set; }
        public string isFever { get; set; }
    
        public virtual tbStu tbStu { get; set; }
        public virtual tbTea tbTea { get; set; }
    }
}
