//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int StuID { get; set; }

        [Required(ErrorMessage ="姓名不能为空")]
        public string Name { get; set; }

        [Required(ErrorMessage ="密码不能为空")]
        [RegularExpression("[A-Za-z0-9]{6,12}",ErrorMessage ="密码6-12位数字，字母组成")]
        public string Password { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Grades { get; set; }


        [MaxLength(20,ErrorMessage ="最长20个字")]
        public string Intro { get; set; }
        public string Agreest { get; set; }
 
        [Compare("Password",ErrorMessage ="两次输入的密码不正确")]
        public string Password2 { get; set; }


        [Range(typeof(int),"10","30",ErrorMessage ="年龄到10-30")]
        public Nullable<int> Age { get; set; }
    
        public virtual Grades Grades1 { get; set; }
    }
}
